### ISSUE TITLE
Metadata?

### ISSUE THREAD

**Issue by jeffsays** [neverendingqs/serverless-default-aws-resource-properties#23]
Hello!  Is there any chance this project will be updated to include supporting default Metadata on resources, in addition to just Properties?

**Comment by neverendingqs** [comment]
I am not familiar with `Metadata`, but this plugin targets `Resources` section as outlined in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html today.

Could you provide a sample `serverless.yml` that shows what you mean by supporting default Metadata on resources? I want to make sure I understand the request here.

**Comment by mwarkentin** [comment]
@neverendingqs I think @jeffsays was referring to this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-metadata.html

For myself, I was actually hoping to use this plugin to set a default [`DeletionPolicy`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) but I don't think I'll be able to since that's at the same level as the resource `Properties`.

**Comment by jeffsays** [comment]
@neverendingqs @mwarkentin is correct - I mean on a per-resource basis, not per-template.

Often times in projects I will add the metadata attribute to a resource to feed information an external tool like [cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint), [cfn_nag](https://github.com/stelligent/cfn_nag) or [checkov](https://github.com/bridgecrewio/checkov) in order to validate templates or ensure conformance to security standards

Here are a couple examples: 
https://github.com/aws-cloudformation/cfn-python-lint#resource-based-metadata
https://github.com/stelligent/cfn_nag#per-resource-rule-suppression

As noted by @mwarkentin, there are a few more resource attributes to the Properties attribute that would be awesome if they replicated as default properties (CreationPolicy, DeletionPolicy, DependsOn, UpdatePolicy, UpdateReplacePolicy)


Right now I need to do something like this:

```yaml
resources:
  Resources:
    myAwesomeResource1:
      Type:  AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Metadata:
        cfn_nag_scan:
          rules_to_suppress:
            - id: W86
              reason: "Keeping logs indefinitely"
    myAwesomeResource2:
      Type:  AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Metadata:
        cfn_nag_scan:
          rules_to_suppress:
            - id: W86
              reason: "Keeping logs indefinitely"
```

It'd be awesome to have something like the following and have it work the way items under the Properties attribute apply to resources of the same type:

```yaml
custom:
  defaultAwsProperties:
    - Type:  AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Metadata:
        cfn_nag_scan:
          rules_to_suppress:
            - id: W86
              reason: "Keeping logs indefinitely"
```

(Thank you for your quick reply originally @neverendingqs - I somehow missed it until the above reply notified me!)
